volumes:
  voting_app_data:
    name: voting_app_data 

services:
  postgres_db:
    container_name: voting_app_db 
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: voting_db
    volumes:
      - voting_app_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "admin", "-d", "voting_db"]
      interval: 10s
      retries: 3
    restart: unless-stopped

  voting_app_backend:
    container_name: voting_app_backend 
    image: hkshub/voting_app_backend 
    environment:
      DATABASE_URL: postgresql://admin:secret@voting_app_db/voting_db
    depends_on:
      postgres_db:
        condition: service_healthy
    cap_drop:
      - ALL
    entrypoint: ["uvicorn"]
    command: [ "app.main:app", "--host", "0.0.0.0", "--port", "8000" ]

  voting_app_frontend:
    container_name: voting_app_frontend  
    image: hkshub/voting_app_frontend 
    environment:
      REACT_APP_API_BASE_URL: https://localhost
    ports:
      - 3000:3000
    depends_on:
      - voting_app_backend
    cap_drop:
      - ALL
    entrypoint: ["npm"]
    command: ["start"]

  voting_app_rev_proxy:
    container_name: voting_app_rev_proxy
    image: nginx:stable-alpine
    volumes:
      - /etc/nginx/certs:/etc/nginx/certs:ro
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 80:80
      - 443:443
    depends_on:
      - voting_app_backend

