name: Devsecops Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  start_pipeline:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Starting the pipeline
        run: echo "Starting the Pipeline"

  pylint_scan:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    needs: start_pipeline
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Running Pylint Scan
        run: >
          docker run
          --rm
          -v ${{github.workspace}}:/workspace
          cytopia/pylint /workspace/backend/app
          | tee pylint_report.txt
          || true

      - name: Uploading Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Pylint Scan'
          path: pylint_report.txt

  flake8_scan:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    needs: start_pipeline
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Running Flake8 Scan
        run: >
          docker run
          --rm
          -v ${{github.workspace}}:/workspace
          alpine/flake8 /workspace/backend/app
          | tee flake8_report.txt
          || true

      - name: Uploading Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Flake8 Scan'
          path: flake8_report.txt

  trivy_scan:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    needs: start_pipeline
    strategy:
      matrix:
        type: [frontend, backend]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Running Trivy Scan
        run: >
          docker run
          --rm
          -v ${{github.workspace}}:/workspace
          aquasec/trivy fs --no-progress --severity HIGH,CRITICAL --output "/workspace/trivy_${{matrix.type}}_report.txt" "/workspace/${{matrix.type}}"
          || true

      - name: Uploading Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Trivy ${{matrix.type}} Scan'
          path: "trivy_${{matrix.type}}_report.txt"

  build_scan_push_images:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        image: [voting_app_backend, voting_app_frontend]
    needs: [flake8_scan, pylint_scan, trivy_scan]
    steps:
      - name: Chekout Code
        uses: actions/checkout@v4

      - name: Building Images
        run: docker compose build ${{matrix.image}}

      - name: Running Trivy Scan
        run: >
          docker run
          --rm
          -v ${{github.workspace}}:/workspace
          -v /var/run/docker.sock:/var/run/docker.sock
          aquasec/trivy image --no-progress --severity HIGH,CRITICAL --output "/workspace/trivy_${{matrix.image}}_image_scan_report.txt" ${{matrix.image}}
          || true

      - name: Uploading Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Trivy ${{matrix.image}} Scan'
          path: "trivy_${{matrix.image}}_image_scan_report.txt"

      - name: Tagging Images
        run: docker tag ${{matrix.image}} "${{secrets.DOCKERHUB_USER}}/${{matrix.image}}"

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: Pushing Images
        run: docker push "${{secrets.DOCKERHUB_USER}}/${{matrix.image}}"

  deploy_app:
    runs-on: self-hosted
    defaults:
      run:
        shell: bash
    needs: build_scan_push_images
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploying Application
        run: docker compose up -d --build

      
